# SPDX-License-Identifier: GPL-2.0+ OR BSD-3-Clause
#
# Copyright (c) 2017-2018, Intel Corporation.
#
# Makefile - HDCP client driver for Intel MEI Bus Driver.

obj-$(CONFIG_INTEL_MEI_HDCP) += mei_hdcp.o
